# Generated by Django 3.1.7 on 2021-03-28 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=1024)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=512)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("car_model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cars.carmodel")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="carmodel",
            name="make",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="car_models", to="cars.make"
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="ratings",
            field=models.ManyToManyField(
                related_name="car_ratings", through="cars.Rating", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
